# -*- coding: utf-8 -*-
"""Image Recognition with Machine Learning using PyTorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NT7PUHiWVEV1hDJteay5lxtiYaQbYEXH
"""

from torchvision import models
dir(models)

alexnet = models.AlexNet()

resnet = models.resnet101(pretrained=True)
resnet

from torchvision import transforms
preprocess = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225]
        )])

from google.colab import files
uploaded = files.upload()

import os
os.rename("/content/dog.png (1).jpeg", "/content/dog.png")

from PIL import Image
img = Image.open("/content/dog.png")
img

img_t = preprocess(img)

import torch
batch_t = torch.unsqueeze(img_t, 0)
resnet.eval()
out = resnet(batch_t)
out

!wget https://raw.githubusercontent.com/pytorch/hub/master/imagenet_classes.txt

with open('imagenet_classes.txt') as f:
    labels = [line.strip() for line in f.readlines()]
_, index = torch.max(out, 1)

percentage = torch.nn.functional.softmax(out, dim=1)[0] * 100
labels[index[0]], percentage[index[0]].item()